const initialState = {
  meal: false,
  dine: [
    {
      name: "cold Dish",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/190326-spicy-salmon-bowl-horizontal-1556024100.png?crop=0.669xw:1.00xh;0.0308xw,0&resize=640:*",
    },
    {
      name: "cold Dish1",
      price: "$2.90",
      price2: "$4.58",
      value: "this meal2 !",
      img: "https://static.toiimg.com/photo/76942221.cms",
    },
    {
      name: "cold Dish2",
      price: "$2.30",
      price2: "$4.58",
      value: "this meal !",
      img: "https://images.indianexpress.com/2021/07/Shalini-July-11-feature-1200.jpg",
    },
    {
      name: "cold Dish3",
      price: "$2.60",
      price2: "$4.58",
      value: "this meal !",
      img: "https://5.imimg.com/data5/DD/PN/EJ/SELLER-40061058/meals-jpg-500x500.jpg",
    },
    {
      name: "cold Dish3",
      price: "$2.60",
      price2: "$4.58",
      value: "this meal !",
      img: "https://5.imimg.com/data5/DD/PN/EJ/SELLER-40061058/meals-jpg-500x500.jpg",
    },
    {
      name: "cold Dish3",
      price: "$2.60",
      price2: "$4.58",
      value: "this meal !",
      img: "https://5.imimg.com/data5/DD/PN/EJ/SELLER-40061058/meals-jpg-500x500.jpg",
    },
  ],
  cold: [
    {
      name: "",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://thumbor.thedailymeal.com/wqcpeBUY3J_y2GYqkUDDeFYFnVI=/870x565/filters:focal(1060x707:1061x708)/https://www.thedailymeal.com/sites/default/files/story/2018/1-_iStock-687156926-1.jpg",
    },
    {
      name: "",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.kidspot.com.au/a4j9tS6J/w643-h428-cfill-q90/kk/2019/12/mango-salad-wreath04-602831-1.jpg",
    },
    {
      name: "",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.kidspot.com.au/2exZiiQq/w643-h428-cfill-q90/kk/2019/08/tuekry-601584-1.jpg",
    },
    {
      name: "Christmas bauble appetisers",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.kidspot.com.au/F4CodfT-/w643-h428-cfill-q90/kk/2015/10/christmas_bauble_appetisers_hero-jpg-505945-1.jpg",
    },
    {
      name: "Brown rice salad",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.kidspot.com.au/3T2gmDBM/w643-h428-cfill-q90/kk/2019/12/brown-rice-salad-602699-1.jpg",
    },
    {
      name: "Crunchy chickpeas",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.kidspot.com.au/FJ7Ts3uP/w643-h428-cfill-q90/kk/2017/09/roastedsweet-potato-pear-salad-recipe-jpg-507094-1.jpg",
    },
  ],
  soup: [
    {
      name: "Mushroom Soup",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://www.recipetineats.com/wp-content/uploads/2021/04/Mushroom-Soup-in-bowl-SQ.jpg",
    },
    {
      name: "Vegitarian Soup",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://img.taste.com.au/JvrmexiB/taste/2016/11/speedy-tuscan-white-bean-soup-111016-1.jpg",
    },
    {
      name: "",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2P5otKsez6PBd9OIKoqKkagChyz-hZcw7DA&usqp=CAU",
    },
    {
      name: " Classic Soup",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/homemade-pumpkin-soup-royalty-free-image-1571855802.jpg",
    },
    {
      name: "Classic Soup",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-Zo9dndL53I1Gtp3LB82aX7uTYSZqIbvmGQ&usqp=CAU",
    },
    {
      name: "Classic Soup",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXO9JiUwLJrPpAbSozG0vych8pVngJ8PZWitYGAXY5LxXPjMjgBZjl8l-ussK-uuGAsUg&usqp=CAU",
    },
  ],
  grill: [
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfYYNJ-LprN-qgcGP4IuAP__FHYzaD_xpa9aJUovszG3wwJtXpBzMkg5EH6Nrf2G302xw&usqp=CAU",
    },
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmqHRRqNj8L4PH5HYpbVBN5lQ4nYx11_54mQ&usqp=CAU",
    },
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNSdq1ssIoUg6vh7X8Ow1b-weFO9neh2Ozmg&usqp=CAU",
    },
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa0ft6m3GNyXrC3mfuojILVtHCUEX9PUDk3A&usqp=CAU",
    },
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyKrqxAFnfiZFZVOyz5IaKmZtJYpAFFxKhsg&usqp=CAU",
    },
    {
      name: "Chicken",
      price: "$2.50",
      price2: "$4.58",
      value: "this meal !",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTftfz2d-xKG5pPnzka5iZFmuVJBEWXGhn7Lw&usqp=CAU",
    },
  ],
};

export default initialState;
